package com.fym.dao;

import com.fym.entity.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    Address selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKey(Address record);
}