package com.fym.dao;

import java.util.List;
import java.util.Map;

import com.fym.entity.Bill;

public interface BillMapper {
	List<Bill> selectAll(Bill bill);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insertSelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    Bill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKeySelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKey(Bill record);
}