package com.fym.dao;

import java.util.List;

import com.fym.entity.Provider;

public interface ProviderMapper {
	
	List<Provider> selectAll(Provider provider);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insert(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insertSelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    Provider selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKeySelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKey(Provider record);
}