package com.fym.dao;

import com.fym.entity.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    int updateByPrimaryKey(Role record);
}