package com.fym.entity;

import java.io.Serializable;
import java.util.Date;

public class Provider implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.id
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proCode
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private String procode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proName
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private String proname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proDesc
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private String prodesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proContact
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private String procontact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proPhone
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private String prophone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proAddress
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private String proaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proFax
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private String profax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.createdBy
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.creationDate
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.modifyDate
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.modifyBy
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    private Long modifyby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.id
     *
     * @return the value of smbms_provider.id
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.id
     *
     * @param id the value for smbms_provider.id
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proCode
     *
     * @return the value of smbms_provider.proCode
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public String getProcode() {
        return procode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proCode
     *
     * @param procode the value for smbms_provider.proCode
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setProcode(String procode) {
        this.procode = procode == null ? null : procode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proName
     *
     * @return the value of smbms_provider.proName
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proName
     *
     * @param proname the value for smbms_provider.proName
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proDesc
     *
     * @return the value of smbms_provider.proDesc
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public String getProdesc() {
        return prodesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proDesc
     *
     * @param prodesc the value for smbms_provider.proDesc
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setProdesc(String prodesc) {
        this.prodesc = prodesc == null ? null : prodesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proContact
     *
     * @return the value of smbms_provider.proContact
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public String getProcontact() {
        return procontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proContact
     *
     * @param procontact the value for smbms_provider.proContact
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setProcontact(String procontact) {
        this.procontact = procontact == null ? null : procontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proPhone
     *
     * @return the value of smbms_provider.proPhone
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public String getProphone() {
        return prophone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proPhone
     *
     * @param prophone the value for smbms_provider.proPhone
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setProphone(String prophone) {
        this.prophone = prophone == null ? null : prophone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proAddress
     *
     * @return the value of smbms_provider.proAddress
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public String getProaddress() {
        return proaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proAddress
     *
     * @param proaddress the value for smbms_provider.proAddress
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setProaddress(String proaddress) {
        this.proaddress = proaddress == null ? null : proaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proFax
     *
     * @return the value of smbms_provider.proFax
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public String getProfax() {
        return profax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proFax
     *
     * @param profax the value for smbms_provider.proFax
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setProfax(String profax) {
        this.profax = profax == null ? null : profax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.createdBy
     *
     * @return the value of smbms_provider.createdBy
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.createdBy
     *
     * @param createdby the value for smbms_provider.createdBy
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.creationDate
     *
     * @return the value of smbms_provider.creationDate
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.creationDate
     *
     * @param creationdate the value for smbms_provider.creationDate
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.modifyDate
     *
     * @return the value of smbms_provider.modifyDate
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.modifyDate
     *
     * @param modifydate the value for smbms_provider.modifyDate
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.modifyBy
     *
     * @return the value of smbms_provider.modifyBy
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public Long getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.modifyBy
     *
     * @param modifyby the value for smbms_provider.modifyBy
     *
     * @mbg.generated Thu Aug 30 14:41:50 CST 2018
     */
    public void setModifyby(Long modifyby) {
        this.modifyby = modifyby;
    }
}